[package]
name = "shouxtech/roactanimation"
description = "A simple animation interface for Roact"
version = "0.1.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
React = "jsdotlua/react@17.2.1"
